### ISSUE TITLE
windows 运行报 exception: An `executablePath` or `channel` must be specified for `puppeteer-core`，Mac没这个问题

### ISSUE THREAD

**Issue by LesterDong** [bincooo/webgpt-bot#3]
19:24:40 ERR PuppetWeChatBridge start() exception: Error: An `executablePath` or `channel` must be specified for `puppeteer-core`19:24:40 ERR PuppetWeChat initBridge() exception: An `executablePath` or `channel` must be specified for `puppeteer-core`
19:24:40 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
GError: An `executablePath` or `channel` must be specified for `puppeteer-core`
    at assert (D:\Users\gdong.CN1\git\webgpt-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\util\assert.js:28:15)
    at ChromeLauncher.launch (D:\Users\gdong.CN1\git\webgpt-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:92:36)
    at PuppeteerNode.launch (D:\Users\gdong.CN1\git\webgpt-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\node\PuppeteerNode.js:154:105)
    at PuppeteerExtra.launch (D:\Users\gdong.CN1\git\webgpt-bot\node_modules\puppeteer-extra\dist\index.cjs.js:128:41)
    at async Bridge.initBrowser (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:109:23)
    at async Bridge.start (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:48:28)
    at async PuppetWeChat.initBridge (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)
    at async PuppetWeChat.onStart (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)
    at async PuppetWeChat.start (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)
    at async PuppetWeChat.start (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet/dist/esm/src/mixins/service-mixin.js:18:13) {
  code: 2,
  details: 'Error: An `executablePath` or `channel` must be specified for `puppeteer-core`\n' +
    '    at assert (D:\\Users\\gdong.CN1\\git\\webgpt-bot\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\util\\assert.js:28:15)\n' +
    '    at ChromeLauncher.launch (D:\\Users\\gdong.CN1\\git\\webgpt-bot\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\node\\ChromeLauncher.js:92:36)\n' +
    '    at PuppeteerNode.launch (D:\\Users\\gdong.CN1\\git\\webgpt-bot\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\node\\PuppeteerNode.js:154:105)\n' +
    '    at PuppeteerExtra.launch (D:\\Users\\gdong.CN1\\git\\webgpt-bot\\node_modules\\puppeteer-extra\\dist\\index.cjs.js:128:41)\n' +
    '    at async Bridge.initBrowser (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:109:23)\n' +
    '    at async Bridge.start (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:48:28)\n' +
    '    at async PuppetWeChat.initBridge (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)\n' +
    '    at async PuppetWeChat.onStart (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)\n' +
    '    at async PuppetWeChat.start (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)\n' +
    '    at async PuppetWeChat.start (file:///D:/Users/gdong.CN1/git/webgpt-bot/node_modules/wechaty-puppet/dist/esm/src/mixins/service-mixin.js:18:13)'

**Comment by LesterDong** [comment]
看了 两个机器node_module中的puppeteer版本不一致 一个是puppeteer13.7.0版本是没问题的(node v18.13.0) 另外一台是puppeteer19.6.4版本(node v18.12.1)

**Comment by bincooo** [comment]
没在win上试过，可以试试：
//case 'win32':
//      return 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'
//case 'darwin':
//     return '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'


const API = new ChatGPTAPIBrowser({
    email: config.email,
    password: config.password,
    debug: false,
    minimize: true,
    proxyServer: config.proxyServer,
    executablePath: '你的chrome浏览器路径'
})
